In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,100,(5,5))

In [3]:
arr

array([[80, 60, 23, 93, 75],
       [15, 33, 60, 60, 66],
       [28, 77, 96, 43,  6],
       [90, 63, 60, 43, 56],
       [ 1, 67, 82,  9, 63]])

In [4]:
# Numpy arrays are mutable
arr[0][3]

93

In [5]:
arr[0][4]=33   #element changed

In [6]:
arr

array([[80, 60, 23, 93, 33],
       [15, 33, 60, 60, 66],
       [28, 77, 96, 43,  6],
       [90, 63, 60, 43, 56],
       [ 1, 67, 82,  9, 63]])

In [7]:
#numpy array can be sliced

In [8]:
arr[2::,2::]

array([[96, 43,  6],
       [60, 43, 56],
       [82,  9, 63]])

In [9]:
#numpy arrays are iterable

In [10]:
for i in arr:
    print(i)

[80 60 23 93 33]
[15 33 60 60 66]
[28 77 96 43  6]
[90 63 60 43 56]
[ 1 67 82  9 63]


In [11]:
# numpy arrays shape,size and ndim attributes

In [12]:
arr.size

25

In [13]:
arr.shape

(5, 5)

In [15]:
arr.ndim

2

In [16]:
arr

array([[80, 60, 23, 93, 33],
       [15, 33, 60, 60, 66],
       [28, 77, 96, 43,  6],
       [90, 63, 60, 43, 56],
       [ 1, 67, 82,  9, 63]])

In [18]:
# 1-D array
arr1=np.random.randint(1,10,6)  

In [19]:
arr1.ndim

1

In [20]:
arr1

array([1, 3, 3, 2, 9, 9])

In [21]:
arr1.shape

(6,)

In [24]:
# Creation of numpy arrays
# 1. by passing list to array() function of numpy
# 2. using arange function
# 3. using rand/randint functions

In [25]:
A1=np.array([1,2,3,4,5,6,7,8,9])

In [26]:
A1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
A2=np.arange(1,26,2)

In [28]:
A2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [29]:
A3=np.random.randint(1,100,20)

In [30]:
A3

array([96, 55, 10, 71, 65, 38, 39,  6, 78, 72, 46, 67, 62, 47, 34, 27, 48,
       86, 89, 72])

In [31]:
A4=np.random.rand(10)

In [32]:
A4

array([0.21643069, 0.26895617, 0.94042376, 0.56742053, 0.11016363,
       0.93094616, 0.52903733, 0.61645193, 0.69949365, 0.02018663])

In [33]:
# shaping array

In [35]:
A1=np.random.randint(1,100,(5,5))

In [36]:
A1

array([[67, 89, 30, 73, 95],
       [26, 43, 89, 56, 34],
       [55, 66, 21, 74, 89],
       [41, 85, 24, 68, 68],
       [44, 82, 25, 93,  1]])

In [37]:
A2=np.arange(1,100,3)

In [38]:
A2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [39]:
A2.size

33

In [41]:
A2.shape=(11,3)

In [42]:
A2

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25],
       [28, 31, 34],
       [37, 40, 43],
       [46, 49, 52],
       [55, 58, 61],
       [64, 67, 70],
       [73, 76, 79],
       [82, 85, 88],
       [91, 94, 97]])

In [43]:
A2.ravel()

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

# Aggregation functions

In [70]:
A1=np.arange(1,100,5)

In [71]:
A1

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [48]:
A1.size 

20

In [49]:
A1.shape=(5,4)

In [50]:
A1

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])

In [51]:
A1*-1

array([[ -1,  -6, -11, -16],
       [-21, -26, -31, -36],
       [-41, -46, -51, -56],
       [-61, -66, -71, -76],
       [-81, -86, -91, -96]])

In [52]:
#original array do not change
A1

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])

In [53]:
A1.min()

1

In [54]:
A1.max()

96

In [55]:
A1[0]

array([ 1,  6, 11, 16])

In [56]:
A1.argmax(axis=1)

array([3, 3, 3, 3, 3], dtype=int64)

In [57]:
A1.max(axis=1)

array([16, 36, 56, 76, 96])

In [58]:
A1.min(axis=0)

array([ 1,  6, 11, 16])

In [60]:
A1.argmin(axis=0)

array([0, 0, 0, 0], dtype=int64)

In [61]:
A1.all()

True

In [62]:
A1.diagonal()

array([ 1, 26, 51, 76])

In [63]:
A1.argsort(axis=0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]], dtype=int64)

In [64]:
A1.sort(axis=0)

In [65]:
A1

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])

In [72]:
A1.flatten()

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [74]:
A1.shape=(5,4)

In [77]:
A1

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])

In [82]:
A1[0][0]

1

In [84]:
A1.item(0)

1

In [85]:
A1.item(3)

16

In [91]:
A4=np.array([10,3,2,8,9,4,5,6,7,1])

In [94]:
A4.partition(5) # it arranges the elements left of 5 --> less than 5
                # and elements right of 5 ----> greater than 5

In [93]:
A4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Boradcasting on numpy arrays

In [95]:
A_1=np.array([[1,1],[2,2],[3,3]])

In [96]:
A_1

array([[1, 1],
       [2, 2],
       [3, 3]])

In [97]:
A_1+[10,10]

array([[11, 11],
       [12, 12],
       [13, 13]])

In [99]:
A_1+10

array([[11, 11],
       [12, 12],
       [13, 13]])

In [100]:
A_1+np.array([[10],[10],[10]])

array([[11, 11],
       [12, 12],
       [13, 13]])

In [101]:
A_random=np.random.randint(1,100,(5,5))

In [102]:
A_random

array([[30, 53, 84, 88, 52],
       [13, 71, 32, 95, 71],
       [55, 82, 26, 17, 38],
       [18, 93, 80, 16, 55],
       [32, 38, 18, 93, 64]])

In [109]:
A_random-1

array([[29, 52, 83, 87, 51],
       [12, 70, 31, 94, 70],
       [54, 81, 25, 16, 37],
       [17, 92, 79, 15, 54],
       [31, 37, 17, 92, 63]])

In [110]:
A_random[A_random<20]

array([13, 17, 18, 16, 18])

In [112]:
A_random

array([[30, 53, 84, 88, 52],
       [13, 71, 32, 95, 71],
       [55, 82, 26, 17, 38],
       [18, 93, 80, 16, 55],
       [32, 38, 18, 93, 64]])

In [119]:
A_random.min(axis=0)

array([13, 38, 18, 16, 38])

In [122]:
new=A_random.flatten()

In [123]:
new

array([30, 53, 84, 88, 52, 13, 71, 32, 95, 71, 55, 82, 26, 17, 38, 18, 93,
       80, 16, 55, 32, 38, 18, 93, 64])

In [127]:
new[(new>20) & (new<80)]

array([30, 53, 52, 71, 32, 71, 55, 26, 38, 55, 32, 38, 64])

In [130]:
np.where(new<20,'less','more')

array(['more', 'more', 'more', 'more', 'more', 'less', 'more', 'more',
       'more', 'more', 'more', 'more', 'more', 'less', 'more', 'less',
       'more', 'more', 'less', 'more', 'more', 'more', 'less', 'more',
       'more'], dtype='<U4')

In [135]:
new.size

25

In [1]:
%time

CPU times: total: 0 ns
Wall time: 0 ns


In [7]:
%%time
a=10
b=100

CPU times: total: 0 ns
Wall time: 0 ns


# in numpy Memory management is in our hand

In [8]:
import numpy as np

In [11]:
arr=np.array([1,2,3,4],dtype='int8')  ##### or we can also say 'np.int16'

In [12]:
arr

array([1, 2, 3, 4], dtype=int8)

In [13]:
arr=np.array([1,2,3,4],dtype='int32')

In [15]:
arr=np.array([1,2,3,4],dtype='int64')

In [16]:
## as given above, we can varry the size of int variable from 8 bit to 64 bits .. ----> memory management************

# Create numpy arrays using tuples

In [17]:
np.array((10,20,30),dtype='int16')

array([10, 20, 30], dtype=int16)

In [18]:
np.array([10,20,30],dtype='int16')

array([10, 20, 30], dtype=int16)

In [19]:
d={'1':100,'2':200,'3':300}

In [20]:
np.array(d)

array({'1': 100, '2': 200, '3': 300}, dtype=object)

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((3,3),dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
n1=np.arange(1,100,5)

In [27]:
n1

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [28]:
n1.size

20

In [29]:
n1.shape=(5,4)

In [30]:
n1

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])

In [37]:
prototype=np.empty((5,5),dtype='int8')

In [38]:
prototype

array([[ 92,   0,  63,   0,  63],
       [  0,  92,   0,  67,   0],
       [ 58,   0,  92,   0,  85],
       [  0, 115,   0, 101,   0],
       [114,   0, 115,   0,  92]], dtype=int8)

In [35]:
np.empty_like(([[1,2,3],
               [1,2,3],
               [1,2,3],]))

array([[1173710064,        345,    3801155],
       [   5570652,    6619251,    7536754],
       [   6357084,    7274605,        108]])

In [39]:
np.empty_like(prototype)

array([[ 92,   0,  63,   0,  63],
       [  0,  92,   0,  67,   0],
       [ 58,   0,  92,   0,  85],
       [  0, 115,   0, 101,   0],
       [114,   0, 115,   0,  92]], dtype=int8)

In [40]:
n1

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])

In [43]:
n1

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])

In [45]:
np.where(n1>60)

(array([3, 3, 3, 3, 4, 4, 4, 4], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

# how np array is efficient in size compared to python array

In [46]:
import sys

In [55]:
py_array=[1,2,3,4]

In [58]:
sys.getsizeof(py_array[0])*len(py_array)

112

In [51]:
np_array=np.array([1,2,3,4,5])

In [59]:
np_array.itemsize*np_array.size

20